version: "3"
services:
  backend:
    build:
      context: builds/backend
    image: usabarashi/ddd-on-python-backend:yyyymmmdd
    container_name: backend 
    hostname: backend 
    environment:
      TZ: "Asia/Tokyo"
    command: tail -f /dev/null
    volumes:
      - ../backend:/opt/ddd-on-python
    #  - /etc/localtime:/etc/localtime:ro
    expose:
      - 8000 # HTTP
    ports:
      - 8000:8000