adapter:
    infrastructure:
        auth:
            CREATE_TOKEN_ENDPOINT: "/auth/token"
            SECRET_KEY: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
            ALGORITHM: "HS256"
            EXPIRE_MINUTES: 30
        mongo:
            URI: "mongodb://root:pasword@datastore:27017"
    interface:
        APPLICATION_NAME: "DDD on Python"
        ALLOW_HOST: "0.0.0.0"
        PORT: 8000